Repository Chapter-3-2-Android/SNS-APP, pull requests merged in 2024-04, with the labels that each got.

#53 fix, feat: 마이페이지 프로필 이미지 User에 저장 기능 구현, 각종 액티비티 Fix
  app/src/main/java/com/agvber/sns_app/model/User.kt
  app/src/main/java/com/agvber/sns_app/ui/MyActivity.kt
  app/src/main/java/com/agvber/sns_app/ui/detail/DetailListViewAdapter.kt
  app/src/main/java/com/agvber/sns_app/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_my.xml
Labels: Fix, Feature

#54 feat: 메인 profile image clipToOutline 적용
  app/src/main/java/com/agvber/sns_app/data/PreviewProvider.kt
  app/src/main/java/com/agvber/sns_app/model/User.kt
  app/src/main/java/com/agvber/sns_app/ui/LogInActivity.kt
  app/src/main/java/com/agvber/sns_app/ui/MyActivity.kt
  app/src/main/java/com/agvber/sns_app/ui/SignupActivity.kt
  app/src/main/java/com/agvber/sns_app/ui/detail/DetailActivity.kt
  app/src/main/java/com/agvber/sns_app/ui/detail/DetailListViewAdapter.kt
  app/src/main/java/com/agvber/sns_app/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_main.xml
Labels: Feature

#57 refactor: 리소스 이미지 변경 및 반영
  app/src/main/java/com/agvber/sns_app/data/PreviewProvider.kt
  app/src/main/java/com/agvber/sns_app/ui/main/MainActivity.kt
  app/src/main/java/com/agvber/sns_app/ui/main/PostAdapter.kt
  app/src/main/res/drawable/img_post1.jpg
  app/src/main/res/drawable/img_post1.png
  app/src/main/res/drawable/img_post10.jpg
  app/src/main/res/drawable/img_post10.png
  app/src/main/res/drawable/img_post11.jpg
  app/src/main/res/drawable/img_post11.png
  app/src/main/res/drawable/img_post12.jpg
  app/src/main/res/drawable/img_post12.png
  app/src/main/res/drawable/img_post13.jpg
  app/src/main/res/drawable/img_post13.png
  app/src/main/res/drawable/img_post14.jpg
  app/src/main/res/drawable/img_post15.jpg
  app/src/main/res/drawable/img_post16.jpg
  app/src/main/res/drawable/img_post17.jpg
  app/src/main/res/drawable/img_post18.jpg
  app/src/main/res/drawable/img_post19.jpg
  app/src/main/res/drawable/img_post2.jpg
  app/src/main/res/drawable/img_post2.png
  app/src/main/res/drawable/img_post20.jpg
  app/src/main/res/drawable/img_post3.jpg
  app/src/main/res/drawable/img_post3.png
  app/src/main/res/drawable/img_post4.jpg
  app/src/main/res/drawable/img_post4.png
  app/src/main/res/drawable/img_post5.jpg
  app/src/main/res/drawable/img_post5.png
  app/src/main/res/drawable/img_post6.jpg
  app/src/main/res/drawable/img_post6.png
  app/src/main/res/drawable/img_post7.jpg
  app/src/main/res/drawable/img_post7.png
  app/src/main/res/drawable/img_post8.jpg
  app/src/main/res/drawable/img_post8.png
  app/src/main/res/drawable/img_post9.jpg
  app/src/main/res/drawable/img_post9.png
  app/src/main/res/drawable/img_profile1.jpg
  app/src/main/res/drawable/img_profile1.png
  app/src/main/res/drawable/img_profile2.jpg
  app/src/main/res/drawable/img_profile2.png
  app/src/main/res/drawable/img_profile3.jpg
  app/src/main/res/drawable/img_profile3.png
  app/src/main/res/drawable/img_profile4.jpg
  app/src/main/res/drawable/img_profile4.png
  app/src/main/res/drawable/img_profile5.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_post_gridview.xml
Labels: Refactor, Design

#60 [Fix] 특정 기기에서 메인 페이지의 상단 일부 UI가 짤리는 이슈 해결
  app/src/main/java/com/agvber/sns_app/ui/main/PostAdapter.kt
  app/src/main/res/layout/activity_main.xml
Labels: Fix, Design

#61 Gradle 패키지 정리하였습니다
  app/build.gradle.kts
Labels: Refactor

#58 refactor: 마이페이지 프로필 사진 원형 구현, Edittext singleLine 추가
  app/src/main/res/drawable/img_round_myprofile.xml
  app/src/main/res/layout/activity_my.xml
Labels: Refactor, Design
